### ISSUE TITLE
openscap addon in snippets

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/kickstart-files#1]
As an operator I request some snippets for the use of scap profiles during the installation of centos/redhat.

maybe this will help:

```
yum|dnf install scap-security-guide
ls /usr/share/scap-security-guide/kickstart/
```

https://www.open-scap.org/tools/oscap-anaconda-addon/doc/

**Comment by daniel-schier** [comment]
won't fix. will be done in a seperate ansible role.
